spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sgi_db?useSSL=false&serverTimezone=America/Lima&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true

jwt.secret=${JWT_SECRET:sgi_utp_secret_key_2026_muy_larga_para_hmac256}
jwt.expiration-ms=86400000

server.port=${PORT:8081}
springdoc.swagger-ui.path=/swagger-ui.html
